### PR TITLE
fix reading decimal values

### PR DESCRIPTION
**Pull request by wtn**
This patch addresses #4.

### CODE REVIEW

**Comment by bigzed** [comment]
Thank you for your MR. Would you be so kind to add a sample and a spec for your fix?

**Comment by wtn** [comment]
@bigzed When I run `spec` I get the following error and I don't know how to resolve it:

```
Failure/Error: require 'mediainfo_native.so'

LoadError:
  cannot load such file -- mediainfo_native.so
```

**Comment by bigzed** [comment]
You are missing the C-extension for the gem. You have to compile it to run the specs.
If you have `libmediainfo-dev` installed, it should be as easy as running `bundle exec rake spec`, it should compile it implicitly. 
Run  `bundle exec rake clean compile` to just compile the extension and display any errors while trying to compile it.

**Comment by wtn** [comment]
Thank you for your help with compiling the C extension.

Conveniently, the project already has a CAF file, which I used in my spec to demonstrate the issue.

**Comment by bigzed** [comment]
Thank you.

**Pull request merged**
